spring.datasource:
    url: "jdbc:mysql://192.168.1.199:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true"
    username: "root"
    password: "fA0iTfSAyZ9YT5WkDfvVoAAHA41gkeYYsdMNqQJFR2eWooxXjg9GWEt9BkaKLt0NkKZfv8/PiQYDpJ9pTSI3NA=="
    connectionProperties: "config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALJUQV+coCweLv6wq+oavcy17n+XYOTo3jBKu3tfKE+1REum9Aihi/SPYLd88eXcdfjq5yawdMK2wJeZxiIVQv0CAwEAAQ=="
server:
  port: 8080